name: Build iSCSIConsole

on:
  workflow_dispatch:
  push:
    branches:
      - autostart

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: dotnet restore ISCSIConsole.sln

      - name: Install ILRepack
        shell: powershell
        run: |
          dotnet tool install --global dotnet-ilrepack --version 2.0.46

      - name: Prepare ILRepack path
        shell: powershell
        run: |
          $tool = Get-Command ilrepack

          Write-Host "ILRepack source:"
          Write-Host $tool.Source

          New-Item -ItemType Directory -Force "C:\Program Files\ILRepack"

          Copy-Item $tool.Source "C:\Program Files\ILRepack\ILRepack.exe"

          Write-Host "Expected file exists:"
          Test-Path "C:\Program Files\ILRepack\ILRepack.exe"

          Get-ChildItem "C:\Program Files\ILRepack"

      - name: Build net472
        run: dotnet build ISCSIConsole/ISCSIConsole.csproj -c Release -f net472 --no-restore

      - name: List build output
        shell: powershell
        run: |
          Get-ChildItem -Recurse ISCSIConsole\bin\Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: iSCSIConsole-net472
          path: ISCSIConsole/bin/Release/net472/**
